[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_APP_TITLE = "Tyre Hero - 24/7 Emergency Tyre Service"
  VITE_EMERGENCY_PHONE = "0800 000 0000"
  VITE_EMAIL = "rescue@tyrehero.co.uk"
  VITE_SERVICE_AREAS = "Slough, Maidenhead, Windsor"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Edge Functions for performance
[[edge_functions]]
  function = "geolocation"
  path = "/api/location"

# Form handling for contact form
[forms]
  contact = "/contact"