# TyreHero Emergency Service - Prometheus Configuration
# Comprehensive monitoring for 99.9% uptime SLA

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'tyrehero-production'
    service: 'emergency-service'
    environment: 'production'
    region: 'eu-west-2'

# Rule files for alerting
rule_files:
  - "alert_rules/*.yml"
  - "recording_rules/*.yml"

# Scrape configurations
scrape_configs:
  # TyreHero Emergency API
  - job_name: 'tyrehero-emergency-api'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    scheme: https
    
    static_configs:
      - targets:
        - 'api.tyrehero.com'
        - 'emergency.tyrehero.com'
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        regex: 'api\.tyrehero\.com'
        target_label: service_type
        replacement: 'api'
      - source_labels: [__address__]
        regex: 'emergency\.tyrehero\.com'
        target_label: service_type
        replacement: 'emergency'

  # Application Load Balancer
  - job_name: 'aws-alb'
    ec2_sd_configs:
      - region: eu-west-2
        port: 80
        filters:
          - name: tag:Name
            values: 
              - 'tyrehero-emergency-alb'
    
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: alb_name
      - source_labels: [__meta_ec2_availability_zone]
        target_label: availability_zone

  # ECS Container Metrics
  - job_name: 'ecs-containers'
    ecs_sd_configs:
      - region: eu-west-2
        cluster: tyrehero-production
        services:
          - tyrehero-emergency-api
        port: 3000
    
    relabel_configs:
      - source_labels: [__meta_ecs_cluster_name]
        target_label: cluster
      - source_labels: [__meta_ecs_service_name]
        target_label: service
      - source_labels: [__meta_ecs_task_definition_family]
        target_label: task_family

  # PostgreSQL Database
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    
    scrape_interval: 30s
    metrics_path: '/metrics'
    
    relabel_configs:
      - target_label: database_type
        replacement: postgresql
      - target_label: database_role
        replacement: primary

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    
    scrape_interval: 30s
    metrics_path: '/metrics'
    
    relabel_configs:
      - target_label: cache_type
        replacement: redis
      - target_label: cache_role
        replacement: primary

  # NGINX/ALB Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    ec2_sd_configs:
      - region: eu-west-2
        port: 9100
        filters:
          - name: tag:Monitoring
            values: 
              - 'enabled'
    
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type
      - source_labels: [__meta_ec2_availability_zone]
        target_label: availability_zone

  # CloudWatch Metrics (via CloudWatch Exporter)
  - job_name: 'cloudwatch'
    static_configs:
      - targets: ['cloudwatch-exporter:9106']
    
    scrape_interval: 60s
    scrape_timeout: 30s
    
    relabel_configs:
      - target_label: metrics_source
        replacement: cloudwatch

  # Emergency Service Specific Metrics
  - job_name: 'emergency-business-metrics'
    static_configs:
      - targets: ['business-metrics-exporter:8080']
    
    scrape_interval: 30s
    metrics_path: '/emergency/metrics'
    
    relabel_configs:
      - target_label: metrics_type
        replacement: business_metrics

  # Synthetic Monitoring (Blackbox Exporter)
  - job_name: 'blackbox-emergency-endpoints'
    metrics_path: /probe
    params:
      module: [http_2xx]
    
    static_configs:
      - targets:
        - https://api.tyrehero.com/health
        - https://emergency.tyrehero.com/health
        - https://api.tyrehero.com/api/emergency/status
        - https://tyrehero.com
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL Certificate Monitoring
  - job_name: 'ssl-certificate-expiry'
    metrics_path: /probe
    params:
      module: [ssl_expiry]
    
    static_configs:
      - targets:
        - api.tyrehero.com:443
        - emergency.tyrehero.com:443
        - tyrehero.com:443
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # DNS Resolution Monitoring
  - job_name: 'dns-resolution'
    metrics_path: /probe
    params:
      module: [dns_tyrehero]
    
    static_configs:
      - targets:
        - api.tyrehero.com
        - emergency.tyrehero.com
        - tyrehero.com
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Geographic Response Time Monitoring
  - job_name: 'geographic-response-time'
    static_configs:
      - targets: ['geo-probe-london:8080']
        labels:
          location: 'london'
          region: 'uk-south'
      - targets: ['geo-probe-manchester:8080']
        labels:
          location: 'manchester'
          region: 'uk-north'
      - targets: ['geo-probe-edinburgh:8080']
        labels:
          location: 'edinburgh'
          region: 'uk-scotland'
    
    scrape_interval: 60s
    metrics_path: '/probe/emergency-endpoints'

  # Third-party Dependencies
  - job_name: 'external-dependencies'
    metrics_path: /probe
    params:
      module: [http_2xx]
    
    static_configs:
      - targets:
        - https://api.stripe.com/v1
        - https://maps.googleapis.com/maps/api
        - https://api.twilio.com/v1
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [__param_target]
        regex: 'https://api\.stripe\.com.*'
        target_label: dependency_type
        replacement: 'payment'
      - source_labels: [__param_target]
        regex: 'https://maps\.googleapis\.com.*'
        target_label: dependency_type
        replacement: 'maps'
      - source_labels: [__param_target]
        regex: 'https://api\.twilio\.com.*'
        target_label: dependency_type
        replacement: 'messaging'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      
      path_prefix: /
      scheme: http
      timeout: 10s

# Remote write for long-term storage
remote_write:
  - url: "https://prometheus-remote-write.eu-west-2.amazonaws.com/workspaces/ws-12345678/api/v1/remote_write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 10
      capacity: 5000
    
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'emergency_.*|tyrehero_.*|api_.*|database_.*|cache_.*'
        action: keep

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 500GB
    wal-compression: true